/**
 * The registry catalog: every shadcn item pmndrs publishes, whichever repo it
 * lives in, listed on the getting-started page, `docs/getting-started/introduction.mdx`.
 *
 * No index of them existed — each repo's `registry.json` knows its own items
 * and nothing else — so this one is assembled from two sources:
 *
 *   registry.json              this repo's items, as `build.mjs` builds them
 *   registry/external.json     a snapshot of the other repos' items
 *
 * The snapshot is committed, and only its metadata — name, type, description,
 * dependencies, never file contents — so `npm run build` and `npm test` stay
 * offline and deterministic: a test that fetched would fail on a plane, and
 * would turn red the moment another repo pushed, on a branch that changed
 * nothing. Refreshing is an explicit step instead:
 *
 *   npm run refresh-catalog
 *
 * which runs this file to re-fetch each listed registry at its ref, then
 * rebuilds. To list another registry, add `{ "repo": "owner/name", "ref": "…" }`
 * to `registry/external.json` and run the same command.
 *
 * `build.mjs` writes the page — only between its two markers, so the prose
 * around the list stays hand-written — and `build.test.mjs` asserts it is
 * current, like every other generated file here. Its version-ref rewrite skips
 * that same region (`outsideCatalog`): the refs the catalog quotes from other
 * repos' items are theirs to bump, not this build's.
 */
import { readFileSync, writeFileSync } from 'node:fs'

/** The committed snapshot of the other repos' registries. */
export const externalUrl = new URL('../registry/external.json', import.meta.url)

/** The docs page the catalog is written into. */
export const pageUrl = new URL('../docs/getting-started/introduction.mdx', import.meta.url)

/**
 * MDX comments, so the markers are invisible on the site. The docs site
 * compiles MDX with JS expressions on, which is what lets a comment in braces
 * through.
 */
export const startMarker = '{/* catalog:start — generated by `npm run build`, edit scripts/catalog.mjs or registry/external.json instead */}'
export const endMarker = '{/* catalog:end */}'

/**
 * The part of an item the catalog shows. Everything else — `files`, `css`,
 * `docs` — is what `shadcn view` is for.
 */
function summarize({ name, type, description, registryDependencies = [] }) {
  return { name, type, description, registryDependencies }
}

/**
 * Registry descriptions are markdown, but this page is MDX, where a bare `{` or
 * `<` opens an expression or a tag and breaks the whole build. Escaped outside
 * inline code only: inside backticks MDX reads them literally, and a backslash
 * there would show.
 */
function escapeMdx(text) {
  return text
    .split('`')
    .map((part, index) => (index % 2 === 1 ? part : part.replace(/[{}<>]/g, '\\$&')))
    .join('`')
}

/**
 * `registry:block` reads `block`: in a table where every type has the prefix,
 * it is noise.
 *
 * @param {string} type
 * @returns {string}
 */
export function humanizeType(type) {
  return type.replace(/^registry:/, '')
}

/**
 * The anchor pmndrs/docs gives a heading — its `rehypeToc`, mirrored: lowercased,
 * runs of whitespace or hyphens as one `-`, and a title seen before suffixed
 * `-1`, `-2`… (github-slugger's algorithm), so two repos publishing the same
 * item name still link to their own section.
 *
 * Every heading of the page goes through it, in page order, as it does on the
 * site: an item named like a heading above it — the page's own, or a repo's —
 * takes the suffixed id, and the table has to link to that one. A fresh slugger
 * per render, since ids are unique per page.
 */
function createSlugger() {
  const occurrences = new Map()

  return (title) => {
    const slug = title.toLowerCase().replace(/\s+|-+/g, '-')
    let id = slug
    while (occurrences.has(id)) {
      const count = (occurrences.get(slug) ?? 0) + 1
      occurrences.set(slug, count)
      id = `${slug}-${count}`
    }
    occurrences.set(id, 0)
    return id
  }
}

/**
 * The titles of the markdown headings in `markdown`, in order — `## Title`
 * lines, skipping fenced code, where a `#` is a shell comment. Plain titles
 * only: inline markup in a heading (backticks, links) is kept as written,
 * where the site would slug its text.
 *
 * @param {string} markdown
 * @returns {string[]}
 */
export function headingTitles(markdown) {
  const titles = []
  let inFence = false
  for (const line of markdown.split('\n')) {
    if (/^\s*```/.test(line)) inFence = !inFence
    if (inFence) continue

    const heading = line.match(/^ {0,3}#{1,6}\s+(.*?)\s*$/)
    if (heading) titles.push(heading[1])
  }
  return titles
}

/**
 * Where a registry's items are defined: its `registry.json` on GitHub, at the
 * ref the install commands are pinned to.
 */
function registrySourceUrl(repo, ref) {
  return `https://github.com/${repo}/blob/${ref}/registry.json`
}

/**
 * The catalog as MDX: a table of every item across registries, then the
 * `search` command that browses every registry at once, then one section per
 * registry, one entry per item, each with the pinned command that installs it.
 *
 * The table holds links only — each name to its section, each registry to its
 * `registry.json` — so no description or dependency is written twice.
 *
 * Its headings start at `###`: the catalog sits in a `##` section of the
 * getting-started page.
 *
 * @param {{ repo: string, ref: string, items: object[] }[]} registries
 *   `repo` is the GitHub `owner/name` the CLI resolves, `ref` the tag or branch
 *   every install command is pinned to.
 * @param {{ headingsAbove?: string[] }} [options]
 *   `headingsAbove` are the titles of the page's headings before the catalog,
 *   whose ids the items' anchors must not take.
 * @returns {string}
 */
export function renderCatalog(registries, { headingsAbove = [] } = {}) {
  // Ids are handed out in page order, so every heading is slugged in the order
  // it is written: the page's own, then the table's and the terminal's — which
  // come first in the catalog — then each registry's, item by item.
  const slug = createSlugger()
  headingsAbove.forEach(slug)

  const tableTitle = 'All items'
  slug(tableTitle)
  const browseTitle = 'Browse from the terminal'
  slug(browseTitle)

  const rows = []
  const sections = registries.map(({ repo, ref, items }) => {
    slug(repo)

    const entries = items.map(summarize).map(({ name, type, description, registryDependencies }) => {
      rows.push([`[${name}](#${slug(name)})`, humanizeType(type), `[${repo}](${registrySourceUrl(repo, ref)})`])

      const dependencies = registryDependencies.length
        ? registryDependencies.map((dependency) => `\`${dependency}\``).join(', ')
        : 'none'

      return [
        `#### ${name}`,
        escapeMdx(description),
        ['```sh', `npx shadcn@latest add ${repo}/${name}#${ref}`, '```'].join('\n'),
        `Type \`${type}\` · registry dependencies: ${dependencies}`,
      ].join('\n\n')
    })

    const source = `[\`registry.json\`](${registrySourceUrl(repo, ref)})`
    return [`### ${repo}`, `${items.length} items, from ${source} at \`${ref}\`.`, ...entries].join('\n\n')
  })

  const table = [
    `### ${tableTitle}`,
    ['| Item | Type | Registry |', '| --- | --- | --- |', ...rows.map((cells) => `| ${cells.join(' | ')} |`)].join('\n'),
  ].join('\n\n')

  // Pinned like the install commands: `search` prints each item's address with
  // the ref it was given, so an unpinned search hands out unpinned addresses.
  const search = registries.map(({ repo, ref }) => `${repo}#${ref}`).join(' ')
  const browse = [
    `### ${browseTitle}`,
    'The CLI lists the same items, read live from each repo at the same refs:',
    ['```sh', `npx shadcn@latest search ${search}`, '```'].join('\n'),
    'and `npx shadcn@latest view <address>` prints an item, files and all, before you add it.',
  ].join('\n\n')

  return [table, browse, ...sections].join('\n\n')
}

/**
 * The positions of `page`'s catalog markers, or `null` when it has none.
 */
function findCatalog(page) {
  const start = page.indexOf(startMarker)
  const end = page.indexOf(endMarker)
  if (start === -1 || end < start) return null

  return { start: start + startMarker.length, end }
}

/**
 * `page` with its catalog — everything between its markers — rendered afresh
 * from `registries`, the prose around it untouched.
 *
 * @param {string} page
 * @param {{ repo: string, ref: string, items: object[] }[]} registries
 * @returns {string}
 */
export function writeCatalog(page, registries) {
  const region = findCatalog(page)
  if (!region) {
    throw new Error(`${pageUrl.pathname} has lost its catalog markers — restore:\n${startMarker}\n${endMarker}`)
  }

  const before = page.slice(0, region.start)
  const catalog = renderCatalog(registries, { headingsAbove: headingTitles(before) })
  return before + '\n\n' + catalog + '\n\n' + page.slice(region.end)
}

/**
 * `page` with `transform` applied to everything but its catalog — the whole
 * page when it has none. How a rewrite of the hand-written prose leaves the
 * generated region as `writeCatalog` wrote it.
 *
 * @param {string} page
 * @param {(text: string) => string} transform
 * @returns {string}
 */
export function outsideCatalog(page, transform) {
  const region = findCatalog(page)
  if (!region) return transform(page)

  return transform(page.slice(0, region.start)) + page.slice(region.start, region.end) + transform(page.slice(region.end))
}

/**
 * Re-fetches every registry `registry/external.json` lists, at its ref, from
 * raw GitHub — the same file the shadcn CLI resolves an address against.
 */
async function refreshExternal() {
  const registries = JSON.parse(readFileSync(externalUrl, 'utf8'))

  const refreshed = []
  for (const { repo, ref } of registries) {
    const url = `https://raw.githubusercontent.com/${repo}/${ref}/registry.json`
    const response = await fetch(url)
    if (!response.ok) throw new Error(`${url}: ${response.status} ${response.statusText}`)

    const { items } = await response.json()
    refreshed.push({ repo, ref, items: items.map(summarize) })
    console.log(`✔ ${repo}#${ref}: ${items.map((item) => item.name).join(', ')}`)
  }

  writeFileSync(externalUrl, JSON.stringify(refreshed, null, 2) + '\n')
}

if (import.meta.main) {
  await refreshExternal()
}
