/**
 * The registry catalog: every shadcn item pmndrs publishes, whichever repo it
 * lives in, listed on `docs/getting-started/registry.mdx`.
 *
 * No index of them existed — each repo's `registry.json` knows its own items
 * and nothing else — so this one is assembled from two sources:
 *
 *   registry.json              this repo's items, as `build.mjs` builds them
 *   registry/external.json     a snapshot of the other repos' items
 *
 * The snapshot is committed, and only its metadata — name, type, description,
 * dependencies, never file contents — so `npm run build` and `npm test` stay
 * offline and deterministic: a test that fetched would fail on a plane, and
 * would turn red the moment another repo pushed, on a branch that changed
 * nothing. Refreshing is an explicit step instead:
 *
 *   npm run refresh-catalog
 *
 * which runs this file to re-fetch each listed registry at its ref, then
 * rebuilds. To list another registry, add `{ "repo": "owner/name", "ref": "…" }`
 * to `registry/external.json` and run the same command.
 *
 * `build.mjs` writes the page — only between its two markers, so the prose
 * around the list stays hand-written — and `build.test.mjs` asserts it is
 * current, like every other generated file here.
 */
import { readFileSync, writeFileSync } from 'node:fs'

/** The committed snapshot of the other repos' registries. */
export const externalUrl = new URL('../registry/external.json', import.meta.url)

/** The docs page the catalog is written into. */
export const pageUrl = new URL('../docs/getting-started/registry.mdx', import.meta.url)

/**
 * MDX comments, so the markers are invisible on the site. The docs site
 * compiles MDX with JS expressions on, which is what lets a comment in braces
 * through.
 */
const startMarker = '{/* catalog:start — generated by `npm run build`, edit scripts/catalog.mjs or registry/external.json instead */}'
const endMarker = '{/* catalog:end */}'

/**
 * The part of an item the catalog shows. Everything else — `files`, `css`,
 * `docs` — is what `shadcn view` is for.
 */
function summarize({ name, type, description, registryDependencies = [] }) {
  return { name, type, description, registryDependencies }
}

/**
 * Registry descriptions are markdown, but this page is MDX, where a bare `{` or
 * `<` opens an expression or a tag and breaks the whole build. Escaped outside
 * inline code only: inside backticks MDX reads them literally, and a backslash
 * there would show.
 */
function escapeMdx(text) {
  return text
    .split('`')
    .map((part, index) => (index % 2 === 1 ? part : part.replace(/[{}<>]/g, '\\$&')))
    .join('`')
}

/**
 * A table cell holds one line, and a bare `|` ends it — so both go, on top of
 * the MDX escaping every description gets. `\|` is GFM's escape, honoured
 * inside inline code too.
 */
function escapeCell(text) {
  return escapeMdx(text).replace(/\s*\n\s*/g, ' ').replace(/\|/g, '\\|')
}

/**
 * The first sentence of a description, for the summary table — the full text
 * is in the item's own section below it. A sentence ends at `.`, `!` or `?`
 * followed by whitespace or the end; a description without one is kept whole.
 *
 * @param {string} description
 * @returns {string}
 */
export function firstSentence(description) {
  const match = description.match(/^[\s\S]*?[.!?](?=\s|$)/)
  return match ? match[0] : description
}

/**
 * `registry:block` reads `block`: in a table where every type has the prefix,
 * it is noise.
 *
 * @param {string} type
 * @returns {string}
 */
export function humanizeType(type) {
  return type.replace(/^registry:/, '')
}

/**
 * The anchor pmndrs/docs gives a heading — its `rehypeToc`, mirrored: lowercased,
 * runs of whitespace or hyphens as one `-`, and a title seen before suffixed
 * `-1`, `-2`… (github-slugger's algorithm), so two repos publishing the same
 * item name still link to their own section.
 *
 * Only the items' headings go through it: the page's other headings — prose,
 * repo names, `All items` — are not item names, so they never take one's id.
 * A fresh slugger per render, since ids are unique per page.
 */
function createSlugger() {
  const occurrences = new Map()

  return (title) => {
    const slug = title.toLowerCase().replace(/\s+|-+/g, '-')
    let id = slug
    while (occurrences.has(id)) {
      const count = occurrences.get(slug) + 1
      occurrences.set(slug, count)
      id = `${slug}-${count}`
    }
    occurrences.set(id, 0)
    return id
  }
}

/**
 * The catalog as MDX: a table of every item across registries, each linked to
 * its section, then the `search` command that browses every registry at
 * once, then one section per registry, one entry per item, each with the
 * pinned command that installs it.
 *
 * @param {{ repo: string, ref: string, items: object[] }[]} registries
 *   `repo` is the GitHub `owner/name` the CLI resolves, `ref` the tag or branch
 *   every install command is pinned to.
 * @returns {string}
 */
export function renderCatalog(registries) {
  // Headings get their anchors in page order, so the slugger walks the items
  // in the order their `###` sections are written below.
  const slug = createSlugger()
  const rows = registries.flatMap(({ repo, items }) =>
    items.map(summarize).map(({ name, type, description, registryDependencies }) => {
      const dependencies = registryDependencies.length
        ? registryDependencies.map((dependency) => `\`${dependency}\``).join(', ')
        : '—'

      const cells = [
        `[${name}](#${slug(name)})`,
        repo,
        humanizeType(type),
        escapeCell(firstSentence(description)),
        dependencies,
      ]
      return `| ${cells.join(' | ')} |`
    })
  )
  const table = [
    '## All items',
    ['| Item | Registry | Type | Summary | Depends on |', '| --- | --- | --- | --- | --- |', ...rows].join('\n'),
  ].join('\n\n')

  const sections = registries.map(({ repo, ref, items }) => {
    const entries = items.map(summarize).map(({ name, type, description, registryDependencies }) => {
      const dependencies = registryDependencies.length
        ? registryDependencies.map((dependency) => `\`${dependency}\``).join(', ')
        : 'none'

      return [
        `### ${name}`,
        escapeMdx(description),
        ['```sh', `npx shadcn@latest add ${repo}/${name}#${ref}`, '```'].join('\n'),
        `Type \`${type}\` · registry dependencies: ${dependencies}`,
      ].join('\n\n')
    })

    const source = `[\`registry.json\`](https://github.com/${repo}/blob/${ref}/registry.json)`
    return [`## ${repo}`, `${items.length} items, from ${source} at \`${ref}\`.`, ...entries].join('\n\n')
  })

  // Pinned like the install commands: `search` prints each item's address with
  // the ref it was given, so an unpinned search hands out unpinned addresses.
  const search = registries.map(({ repo, ref }) => `${repo}#${ref}`).join(' ')
  const browse = [
    '## Browse from the terminal',
    'The CLI lists the same items, read live from each repo at the same refs:',
    ['```sh', `npx shadcn@latest search ${search}`, '```'].join('\n'),
    'and `npx shadcn@latest view <address>` prints an item, files and all, before you add it.',
  ].join('\n\n')

  return [table, browse, ...sections].join('\n\n')
}

/**
 * `page` with everything between its markers replaced by `catalog`.
 *
 * @param {string} page
 * @param {string} catalog
 * @returns {string}
 */
export function spliceCatalog(page, catalog) {
  const start = page.indexOf(startMarker)
  const end = page.indexOf(endMarker)
  if (start === -1 || end < start) {
    throw new Error(`${pageUrl.pathname} has lost its catalog markers — restore:\n${startMarker}\n${endMarker}`)
  }

  return page.slice(0, start + startMarker.length) + '\n\n' + catalog + '\n\n' + page.slice(end)
}

/**
 * Re-fetches every registry `registry/external.json` lists, at its ref, from
 * raw GitHub — the same file the shadcn CLI resolves an address against.
 */
async function refreshExternal() {
  const registries = JSON.parse(readFileSync(externalUrl, 'utf8'))

  const refreshed = []
  for (const { repo, ref } of registries) {
    const url = `https://raw.githubusercontent.com/${repo}/${ref}/registry.json`
    const response = await fetch(url)
    if (!response.ok) throw new Error(`${url}: ${response.status} ${response.statusText}`)

    const { items } = await response.json()
    refreshed.push({ repo, ref, items: items.map(summarize) })
    console.log(`✔ ${repo}#${ref}: ${items.map((item) => item.name).join(', ')}`)
  }

  writeFileSync(externalUrl, JSON.stringify(refreshed, null, 2) + '\n')
}

if (import.meta.main) {
  await refreshExternal()
}
