/**
 * The registry catalog: every shadcn item pmndrs publishes, whichever repo it
 * lives in, listed on the getting-started page, `docs/getting-started/introduction.mdx`.
 *
 * No index of them existed — each repo's `registry.json` knows its own items
 * and nothing else — so this one is assembled from two sources:
 *
 *   registry.json              this repo's items, as `build.mjs` builds them
 *   registry/external.json     a snapshot of the other repos' items
 *
 * The catalog is a table of links and nothing more: each item to its source,
 * each registry to its `registry.json`. Descriptions, dependencies and files
 * stay in the repo that owns them, so the catalog never repeats — and never
 * contradicts — what that repo says.
 *
 * The snapshot is committed, and only what the table shows — name and type —
 * so `npm run build` and `npm test` stay offline and deterministic: a test that
 * fetched would fail on a plane, and would turn red the moment another repo
 * pushed, on a branch that changed nothing. Refreshing is an explicit step
 * instead:
 *
 *   npm run refresh-catalog
 *
 * which runs this file to re-fetch each listed registry at its ref, then
 * rebuilds. To list another registry, add `{ "repo": "owner/name", "ref": "…" }`
 * to `registry/external.json` and run the same command.
 *
 * `build.mjs` writes the page — only between its two markers, so the prose
 * around the table stays hand-written — and `build.test.mjs` asserts it is
 * current, like every other generated file here.
 */
import { readFileSync, writeFileSync } from 'node:fs'

/** The committed snapshot of the other repos' registries. */
export const externalUrl = new URL('../registry/external.json', import.meta.url)

/** The docs page the catalog is written into. */
export const pageUrl = new URL('../docs/getting-started/introduction.mdx', import.meta.url)

/**
 * MDX comments, so the markers are invisible on the site. The docs site
 * compiles MDX with JS expressions on, which is what lets a comment in braces
 * through.
 */
export const startMarker = '{/* catalog:start — generated by `npm run build`, edit scripts/catalog.mjs or registry/external.json instead */}'
export const endMarker = '{/* catalog:end */}'

/** The part of an item the catalog shows. */
function summarize({ name, type }) {
  return { name, type }
}

/**
 * `registry:block` reads `block`: in a table where every type has the prefix,
 * it is noise.
 *
 * @param {string} type
 * @returns {string}
 */
export function humanizeType(type) {
  return type.replace(/^registry:/, '')
}

/**
 * Where an item's source lives: its folder, `registry/<name>/`, on GitHub at
 * the ref to install it from. Every pmndrs registry keeps its items that way —
 * by name rather than by `files[].path`, since an item can have no files at
 * all (`md3` is CSS and docs only), and the folder is where its docs sit.
 *
 * @param {string} repo
 * @param {string} ref
 * @param {string} name
 * @returns {string}
 */
export function itemSourceUrl(repo, ref, name) {
  return `https://github.com/${repo}/tree/${ref}/registry/${name}`
}

/**
 * Where a registry's items are defined: its `registry.json` on GitHub, at the
 * ref to install them from.
 *
 * @param {string} repo
 * @param {string} ref
 * @returns {string}
 */
export function registrySourceUrl(repo, ref) {
  return `https://github.com/${repo}/blob/${ref}/registry.json`
}

/**
 * The catalog as MDX: a table of every item across registries, then the
 * `search` command that lists them all from the terminal.
 *
 * @param {{ repo: string, ref: string, items: { name: string, type: string }[] }[]} registries
 *   `repo` is the GitHub `owner/name` the CLI resolves, `ref` the tag or branch
 *   to install its items from.
 * @returns {string}
 */
export function renderCatalog(registries) {
  const rows = registries.flatMap(({ repo, ref, items }) =>
    items.map(({ name, type }) => {
      const item = `[${name}](${itemSourceUrl(repo, ref, name)})`
      const registry = `[${repo}](${registrySourceUrl(repo, ref)})`
      return `| ${item} | ${humanizeType(type)} | ${registry} |`
    }),
  )
  const table = ['| Item | Type | Registry |', '| --- | --- | --- |', ...rows].join('\n')

  // Pinned like an install command: `search` prints each item's address with
  // the ref it was given, so an unpinned search hands out unpinned addresses.
  const addresses = registries.map(({ repo, ref }) => `${repo}#${ref}`).join(' ')
  const search = ['```sh', `npx shadcn@latest search ${addresses}`, '```'].join('\n')

  return [table, 'The CLI lists the same items, read live from each repo at the ref to pin:', search].join('\n\n')
}

/**
 * `page` with its catalog — everything between its markers — rendered afresh
 * from `registries`, the prose around it untouched.
 *
 * @param {string} page
 * @param {{ repo: string, ref: string, items: { name: string, type: string }[] }[]} registries
 * @returns {string}
 */
export function writeCatalog(page, registries) {
  const start = page.indexOf(startMarker)
  const end = page.indexOf(endMarker)
  if (start === -1 || end < start) {
    throw new Error(`${pageUrl.pathname} has lost its catalog markers — restore:\n${startMarker}\n${endMarker}`)
  }

  const before = page.slice(0, start + startMarker.length)
  return before + '\n\n' + renderCatalog(registries) + '\n\n' + page.slice(end)
}

/**
 * Re-fetches every registry `registry/external.json` lists, at its ref, from
 * raw GitHub — the same file the shadcn CLI resolves an address against.
 */
async function refreshExternal() {
  const registries = JSON.parse(readFileSync(externalUrl, 'utf8'))

  const refreshed = []
  for (const { repo, ref } of registries) {
    const url = `https://raw.githubusercontent.com/${repo}/${ref}/registry.json`
    const response = await fetch(url)
    if (!response.ok) throw new Error(`${url}: ${response.status} ${response.statusText}`)

    const { items } = await response.json()
    refreshed.push({ repo, ref, items: items.map(summarize) })
    console.log(`✔ ${repo}#${ref}: ${items.map((item) => item.name).join(', ')}`)
  }

  writeFileSync(externalUrl, JSON.stringify(refreshed, null, 2) + '\n')
}

if (import.meta.main) {
  await refreshExternal()
}
