/**
 * The `v0` item's stylesheet: the theme without the machinery v0 cannot run.
 * `build.mjs` writes it to `registry/v0/globals.css`; what it is made of is
 * this module's story.
 *
 * Where the CLI path writes the remap (`--primary: var(--md-sys-color-primary)`)
 * and the palette it points at, this writes the end of each chain: shadcn's
 * variables, the ones the remap sets, as the literal colours the bake gives
 * their MD3 role, in a `:root` and a `.dark`. No `--md-*` reaches v0, which
 * is trained on shadcn's names anyway. The rest is the frame shadcn's own Open
 * in v0 payload writes: the imports, the `@theme inline` mapping with the
 * `--radius-*` scale shadcn derives, and the base layer, plus the two fonts
 * from their Fontsource packages, under the families those register.
 */
import { registersFamily } from './packages.mjs'
import { readRemap, tailwindColors } from './remap.mjs'

/**
 * A palette variable followed through its `var()` aliases to the colour.
 *
 * @param {Record<string, string>} block
 * @param {string} name
 */
function literal(block, name) {
  let value = block[name]
  for (let ref; (ref = value?.match(/^var\((--[\w-]+)\)$/)); ) value = block[ref[1]]
  if (!value) throw new Error(`${name} resolves to nothing in the bake`)
  return value
}

/**
 * shadcn's `--radius-*` scale, as the Radius page gives it: every step it
 * derives from `--radius`, by its formula. `--radius-xs` is Tailwind's own
 * rather than derived, so it stays out, as it does in shadcn's.
 *
 * @param {ReturnType<typeof import('./foundations.mjs').readFoundations>['radius']} radius
 */
const radiusScale = (radius) =>
  radius.scale.filter(({ formula }) => formula.includes('var(--radius)')).map(({ token, formula }) => [token, formula])

/**
 * The sans font as the preset installs it, through shadcn's `font-inter`: the
 * Typography page's sans family, under the name its Fontsource package
 * registers (`'Inter Variable', sans-serif`), and that package.
 *
 * @param {ReturnType<typeof import('./foundations.mjs').readFoundations>} foundations
 */
export function sansFont({ typography }) {
  const { family } = typography.fonts.find(({ variable }) => variable === '--font-sans')
  const font = { family: `'${family} Variable', sans-serif`, dependency: `@fontsource-variable/${family.toLowerCase()}` }
  // The name is Fontsource's convention, not something the page says: hold it to the package.
  if (!registersFamily(font.dependency, font.family)) throw new Error(`${font.dependency} registers no ${font.family}`)
  return font
}

/**
 * The `globals.css` of a v0 project, from the baked palette.
 *
 * @param {{ ':root': Record<string, string>, '.dark': Record<string, string> }} palette the bake, `.dark` carrying only what differs from `:root`
 * @param {ReturnType<typeof import('./foundations.mjs').readFoundations>} foundations
 * @param {{ family: string, dependency: string }} mono the `font-mono` item's font
 */
export function v0GlobalsCss(palette, foundations, mono) {
  const remap = readRemap()
  const sans = sansFont(foundations)
  const modes = { ':root': palette[':root'], '.dark': { ...palette[':root'], ...palette['.dark'] } }
  const declarations = (entries) => entries.map(([name, value]) => `  ${name}: ${value};`).join('\n')

  return `/*
 * The pmndrs theme for a v0 project, generated by pmndrs/design-system: do not edit.
 * Colours are the pmndrs palette resolved to literal values; in your own project,
 * install the \`theme\` or \`preset\` registry item instead.
 */
@import "tailwindcss";
@import "tw-animate-css";
@import "shadcn/tailwind.css";
@import "${sans.dependency}";
@import "${mono.dependency}";

@custom-variant dark (&:is(.dark *));

@theme inline {
${declarations([
  ['--font-sans', sans.family],
  ['--font-heading', 'var(--font-sans)'],
  ['--font-mono', mono.family],
  ...tailwindColors(remap),
  ...radiusScale(foundations.radius),
])}
}

:root {
${declarations([['--radius', foundations.radius.base], ...remap.map(({ name, role }) => [name, literal(modes[':root'], role)])])}
}

.dark {
${declarations(remap.map(({ name, role }) => [name, literal(modes['.dark'], role)]))}
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground;
  }
  html {
    @apply font-sans;
  }
  code,
  kbd,
  samp,
  pre {
    @apply font-mono;
  }
}
`
}
